from enum import Enum

class EventHead(Enum):
    END_SESSION = 0
    START_AGENT_SELECT_EVENT = 1
    UPDATE_REMAINING_SELECT_TIME_EVENT = 2
    GAME_START_EVENT = 3
    UPDATE_GAMESTATE_EVENT = 4

class RequestHead(Enum):
    PING_REQUEST = 100
    SELECT_AGENT = 101
    MOVEMENT_REQUEST = 102
    TURN_TO_REQUEST = 103
    SET_WALK_REQUEST = 104
    SET_CROUCH_REQUEST = 105

class MessageHead(Enum):
    PING = 200
    INITIATED = 201
    CONNECTED = 202
    HOSTED = 203
    CLIENT_CONNECTED = 204
    DISCONNECTED = 205
    OPEN_SERVER_AGENT_SELECT = 206
    LEAVE = 207
    JOIN = 208
    HOST = 209
    START = 210
    SELECT_AGENT = 211
    FORCE_START = 212
    START_AGENT_SELECT = 213
    END_AGENT_SELECT = 214
    UPDATE_REMAINING_SELECT_TIME = 215
    SERVER_GAME_START = 216
    CAST_UPDATE_GAMESTATE_EVENT = 217
    SEND_INPUT_REQUESTS = 218
    SEND_TURN_REQUEST = 219
    FORCE_DISCONNECT = 220