from enum import Enum

class EventHead(Enum):
    END_SESSION = 0
    START_AGENT_SELECT_EVENT = 1
    UPDATE_REMAINING_SELECT_TIME_EVENT = 2
    GAME_START_EVENT = 3
    UPDATE_GAMESTATE_EVENT = 4

class RequestHead(Enum):
    PING_REQUEST = 100
    SELECT_AGENT = 101
    MOVEMENT_REQUEST = 102
    TURN_TO_REQUEST = 103
    SET_WALK_REQUEST = 104
    SET_CROUCH_REQUEST = 105

class MessageHead(Enum):
    PING = 200
    INITIATED = 201
    CONNECTED = 202
    HOSTED = 203
    CLIENT_CONNECTED = 204
    DISCONNECTED = 205
    OPEN_SERVER_AGENT_SELECT = 206
    LEAVE = 207
    JOIN = 208
    HOST = 209
    START = 210
    SELECT_AGENT = 211
    FORCE_START = 212
    START_AGENT_SELECT = 213
    END_AGENT_SELECT = 214
    UPDATE_REMAINING_SELECT_TIME = 215
    SERVER_GAME_START = 216
    CAST_UPDATE_GAMESTATE_EVENT = 217
    SEND_INPUT_REQUESTS = 218
    SEND_TURN_REQUEST = 219
    FORCE_DISCONNECT = 220

# 🔄 🛠️ 📅

class DebugProblem(Enum):
    UNHANDLED_MESSAGE = 1
    UNHANDLED_EVENT = 2
    UNHANDLED_REQUEST = 3
    HANDLING_MESSAGE = 4
    HANDLING_EVENT = 5
    HANDLING_REQUEST = 6
    INITIATED = 7
    CLIENT_CONNECTED = 8
    CONNECTION_LOST = 9
class DebugReason(Enum):
    INVALID_MESSAGE_HEAD = 1
    INVALID_EVENT_HEAD = 2
    INVALID_REQUEST_HEAD = 3
    NO_MATCHING_MESSAGE_HEAD = 4
    NO_MATCHING_EVENT_HEAD = 5
    NO_MATCHING_REQUEST_HEAD = 6
    EXPECTED = 7
    CYCLE = 8
    COMM_IS_NONE = 9
    COMM_NOT_INITIALIZED = 10
    SESSION_ENDED = 11
class DebugDetails(Enum):
    EMPTY = 0
    MESSAGE_HEAD = 1
    EVENT_HEAD = 2
    REQUEST_HEAD = 3
    FULL_MESSAGE = 4
    FULL_EVENT = 5
    FULL_REQUEST = 6
    CLIENT_NAME = 7
    CLIENT_NAME_IS_NONE = 8

debugProblems: dict[DebugProblem, str] = {}

debugReasons: dict[DebugReason, str] = {}

debugDetails: dict[DebugDetails, str] = {}